name: testing CI in github

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - checkout: checkout projeto
        uses: actions/checkout@v2

      - name: setup node.js enviroment
        uses: actions/setup-node@2.2.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: npm install

      - name: run test
        run: npm run test 
        