name: Continuos Integration

on:
  push:
    branches: [ main ]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - name: checkout projeto
      - uses: actions/checkout@v3

      - name: setup node.js enviroment
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: install dependencies and run test
        run: |
          npm install
          npm run test
        